FROM docker:dind

RUN apk add py3-pip

RUN apk add gcc musl-dev python3-dev libffi-dev openssl-dev cargo make

RUN pip install --upgrade pip

RUN pip install azure-cli

RUN rm -rf /root/.azure/

COPY ./.azure/ /root/.azure/

